// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Masters of Doom: How Two Guys Created an Empire and Transformed Pop Culture is a 2003 book by David Kushner about video game company id Software and its influence on popular culture, focusing on co-founders John Carmack and John Romero.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/5/53/Masters_of_doom-Book_cover.jpg",
                            Price = 9.99m,
                            Title = "Masters of Doom"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Foucault's Pendulum (original title: Il pendolo di Foucault [il ˈpɛndolo di fuˈko]) is a novel by Italian writer and philosopher Umberto Eco. It was first published in 1988, and an English translation by William Weaver appeared a year later.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/09/FoucaultsPendulum.jpg",
                            Price = 7.49m,
                            Title = "Foucault's Pendulum"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Morals and Dogma of the Ancient and Accepted Scottish Rite of Freemasonry, or simply Morals and Dogma, is a book of esoteric philosophy published by the Supreme Council, Thirty Third Degree, of the Scottish Rite, Southern Jurisdiction of the United States",
                            ImageUrl = "https://moly.hu/system/covers/big/covers_460628.jpg",
                            Price = 19.99m,
                            Title = "Morals and Dogma"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
